version: '3'

services:
  api:
    build: api
    tty: true
    ports:
      - "5000:5000"
    command: python3.7 api.py

  server:
    build: server
    tty: true
    ports:
      - "8080:8080"
    command: python3.7 server.py

